### ISSUE TITLE
ZTT_C_TASKS CDS

### ISSUE THREAD

**Issue by monty79** [jrodriguez-rc/abap-tasks-tracker#2]
The ZTT_C_TASKS CDS view did not activate in IDES system (7.50 on MS SQL Server ) with SQL error 8116: "argument data type tinyint is invalid for argument 1 of substring function" in this place. 
>         @Consumption.valueHelp:'_criticality'
>         cast(substring(cast( case when plan_end_date <> '00000000'
>                       then case when secondsToDeadline <= 0 then 1
>                                 when secondsToDeadline between 0 and 86400 then 2
>                                 else 3
>                               end
>                       else 0 end as abap.char(3) ),1,1) as ztt_task_criticality )
>             as endCritically,

Maybe substring( ) is not supported on MSSQL? When it is removed, compiled OK:
>         cast(cast( case when plan_end_date <> '00000000'
>                       then case when secondsToDeadline <= 0 then 1
>                                 when secondsToDeadline between 0 and 86400 then 2
>                                 else 3
>                               end
>                       else 0 end as abap.char(3) ) as ztt_task_criticality )

**Comment by jrodriguez-rc** [comment]
I made a change to simplify endCritically, can you check?

**Comment by monty79** [comment]
Just checked new version, compiled OK!
