### ISSUE TITLE
Object type BOBF and SUSH not supported in abapGit

### ISSUE THREAD

**Issue by justrockstar** [jrodriguez-rc/abap-tasks-tracker#3]
Dear Jaime,
Thank you for the nice tool.
I want to import it with the latest version of abapGit into out NW 7.5 SP 16 (09/2019).

When pulling abapGit throws the following errors:

- Object type BOBF not supported, serialize; Import of object ZTT_I_PROJECTS failed 
- Object type BOBF not supported, serialize; Import of object ZTT_I_TASKS failed 
- Object type SUSH not supported, serialize; Import of object D5F4A85E043C2ECB975350C9BF5299HT failed

Do you have any idea to resolve?
Does is need manual steps to bring in the BOPF objects?

Thanks,
Justrockstar

**Comment by jrodriguez-rc** [comment]
You need to install first [larshp/abapGit-Plugins](https://github.com/larshp/abapGit-Plugins)
