### ISSUE TITLE
Object type SUSH not supported, serialize 

### ISSUE THREAD

**Issue by rjbhayani** [jrodriguez-rc/abap-tasks-tracker#4]
Object type BOBF not supported, serialize 

Import of object ZTT_I_PROJECTS failed 

Object type BOBF not supported, serialize 

Import of object ZTT_I_TASKS failed 

Object type SUSH not supported, serialize 

Import of object D5F4A85E043C2ECB975350C9BF5299HT failed

**Comment by jrodriguez-rc** [comment]
You need to install first [abapGit plugins](https://github.com/abapGit/abapGit-Plugins) repository.
